services:
  db:
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=password
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - 127.0.0.1:4318:4318
      - 127.0.0.1:14268:14268
      - 127.0.0.1:16686:16686

  simulate-ui:
    build: frontend
    profiles:
      - simulate-traffic
    environment:
      - DEBUG

volumes:
  pgdata: {}
